src/Entity/Race.php
<?php

namespace App\Entity;

use App\Repository\RaceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RaceRepository::class)
 */
class Race extends Speciality
{
    /**
     * @ORM\Column(type="float")
     */
    private $max_size;

    /**
     * @ORM\Column(type="float")
     */
    private $min_size;

    /**
     * @ORM\OneToMany(targetEntity=Entity::class, mappedBy="race")
     */
    private $entities;

    public function __construct()
    {
        $this->entities = new ArrayCollection();
    }

    public function getMaxSize(): ?float
    {
        return $this->max_size;
    }

    public function setMaxSize(float $max_size): self
    {
        $this->max_size = $max_size;

        return $this;
    }

    public function getMinSize(): ?float
    {
        return $this->min_size;
    }

    public function setMinSize(float $min_size): self
    {
        $this->min_size = $min_size;

        return $this;
    }

    /**
     * @return Collection|Entity[]
     */
    public function getEntities(): Collection
    {
        return $this->entities;
    }

    public function addEntity(Entity $entity): self
    {
        if (!$this->entities->contains($entity)) {
            $this->entities[] = $entity;
            $entity->setRace($this);
        }

        return $this;
    }

    public function removeEntity(Entity $entity): self
    {
        if ($this->entities->removeElement($entity)) {
            // set the owning side to null (unless already changed)
            if ($entity->getRace() === $this) {
                $entity->setRace(null);
            }
        }

        return $this;
    }
}

src/Entity/Speciality.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\SpecialityRepository;
use Doctrine\ORM\Mapping\InheritanceType;
use Doctrine\ORM\Mapping\DiscriminatorMap;
use Doctrine\ORM\Mapping\DiscriminatorColumn;

/**
 * @ORM\Entity(repositoryClass=SpecialityRepository::class)
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @DiscriminatorColumn(name="type", type="string")
 * @DiscriminatorMap({"element" = "Element", "race" = "Race", "typeClass" = "TypeClass"})
 */
abstract class Speciality
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $rate_physical_attack;

    /**
     * @ORM\Column(type="float")
     */
    private $rate_magic_attack;

    /**
     * @ORM\Column(type="float")
     */
    private $rate_physical_resistance;

    /**
     * @ORM\Column(type="float")
     */
    private $rate_magic_resistance;

    /**
     * @ORM\Column(type="float")
     */
    private $rate_physical_stamina;

    /**
     * @ORM\Column(type="float")
     */
    private $rate_magic_stamina;

    /**
     * @ORM\Column(type="float")
     */
    private $rate_speed;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getRatePhysicalAttack(): ?float
    {
        return $this->rate_physical_attack;
    }

    public function setRatePhysicalAttack(float $rate_physical_attack): self
    {
        $this->rate_physical_attack = $rate_physical_attack;

        return $this;
    }

    public function getRateMagicAttack(): ?float
    {
        return $this->rate_magic_attack;
    }

    public function setRateMagicAttack(float $rate_magic_attack): self
    {
        $this->rate_magic_attack = $rate_magic_attack;

        return $this;
    }

    public function getRatePhysicalResistance(): ?float
    {
        return $this->rate_physical_resistance;
    }

    public function setRatePhysicalResistance(float $rate_physical_resistance): self
    {
        $this->rate_physical_resistance = $rate_physical_resistance;

        return $this;
    }

    public function getRateMagicResistance(): ?float
    {
        return $this->rate_magic_resistance;
    }

    public function setRateMagicResistance(float $rate_magic_resistance): self
    {
        $this->rate_magic_resistance = $rate_magic_resistance;

        return $this;
    }

    public function getRatePhysicalStamina(): ?float
    {
        return $this->rate_physical_stamina;
    }

    public function setRatePhysicalStamina(float $rate_physical_stamina): self
    {
        $this->rate_physical_stamina = $rate_physical_stamina;

        return $this;
    }

    public function getRateMagicStamina(): ?float
    {
        return $this->rate_magic_stamina;
    }

    public function setRateMagicStamina(float $rate_magic_stamina): self
    {
        $this->rate_magic_stamina = $rate_magic_stamina;

        return $this;
    }

    public function getRateSpeed(): ?float
    {
        return $this->rate_speed;
    }

    public function setRateSpeed(float $rate_speed): self
    {
        $this->rate_speed = $rate_speed;

        return $this;
    }
}

src/Form/RaceType.php
<?php

namespace App\Form;

use App\Entity\Race;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class RaceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class)
            ->add('description', TextareaType::class)
            ->add('rate_physical_attack', NumberType::class, [
                'label' => false
            ])
            ->add('rate_magic_attack', NumberType::class, [
                'label' => false
            ])
            ->add('rate_physical_resistance', NumberType::class, [
                'label' => false
            ])
            ->add('rate_magic_resistance', NumberType::class, [
                'label' => false
            ])
            ->add('rate_physical_stamina', NumberType::class, [
                'label' => false
            ])
            ->add('rate_magic_stamina', NumberType::class, [
                'label' => false
            ])
            ->add('rate_speed', NumberType::class)
            ->add('max_size', NumberType::class)
            ->add('min_size', NumberType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Race::class,
        ]);
    }
}

src/Controller/RaceController.php
<?php

namespace App\Controller;

use App\Entity\Race;
use App\Form\RaceType;
use App\Repository\RaceRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/race")
 */
class RaceController extends AbstractController
{
    /**
     * @Route("/", name="race_index", methods={"GET"})
     */
    public function index(RaceRepository $raceRepository): Response
    {
        $race = $raceRepository->findAll();
        
        return $this->render('race/index.html.twig', [
            'races' => $race,
        ]);
    }

    /**
     * @Route("/new", name="race_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $race = new Race();
        $form = $this->createForm(RaceType::class, $race);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($race);
            $entityManager->flush();

            return $this->redirectToRoute('race_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('race/new.html.twig', [
            'race' => $race,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="race_show", methods={"GET"})
     */
    public function show(Race $race): Response
    {
        return $this->render('race/show.html.twig', [
            'race' => $race,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="race_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Race $race, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(RaceType::class, $race);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('race_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('race/edit.html.twig', [
            'race' => $race,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="race_delete", methods={"POST"})
     */
    public function delete(Request $request, Race $race, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$race->getId(), $request->request->get('_token'))) {
            $entityManager->remove($race);
            $entityManager->flush();
        }

        return $this->redirectToRoute('race_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/race/_delete_form.html.twig
<form method="post" action="{{ path('race_delete', {'id': race.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ race.id) }}">
    <button class="btn">Delete</button>
</form>

templates/race/_form.html.twig
{{ form_start(form) }}
    {{ form_row(form.name, {'attr' : {'class': 'form-control'}} ) }}
    {{ form_row(form.description, {'attr' : {'class': 'form-control'}} ) }}
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Pourcentage</th>
                <th scope="col">Physique</th>
                <th scope="col">Magique</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">Attaque</th>
                <td>{{ form_row(form.rate_physical_attack, {'attr' : {'class': 'form-control'}} ) }}</td>
                <td>{{ form_row(form.rate_magic_attack, {'attr' : {'class': 'form-control'}} ) }}</td>
            </tr>
            <tr>
                <th scope="row">Resistance</th>
                <td>{{ form_row(form.rate_physical_resistance, {'attr' : {'class': 'form-control'}} ) }}</td>
                <td>{{ form_row(form.rate_magic_resistance, {'attr' : {'class': 'form-control'}} ) }}</td>
            </tr>
            <tr>
                <th scope="row">Endurance</th>
                <td>{{ form_row(form.rate_physical_stamina, {'attr' : {'class': 'form-control'}} ) }}</td>
                <td>{{ form_row(form.rate_magic_stamina, {'attr' : {'class': 'form-control'}} ) }}</td>
            </tr>
        </tbody>
    </table>
    {{ form_row(form.rate_speed, {'attr' : {'class': 'form-control'}} ) }}
    <table class="table table-hover">
        <tbody>
                <tr>
                    <th scope="col">Taille</th>
                    <td> {{ form_row(form.min_size, {'label': 'minimum', 'attr' : {'class': 'form-control'}} ) }}</td>
                    <td> {{ form_row(form.max_size, {'label': 'maximum', 'attr' : {'class': 'form-control'}} ) }}</td>
                </tr>
        </tbody>
    </table>
    <button class="btn btn-sg btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/race/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Race{% endblock %}

{% block body %}
    <h1>Edit Race</h1>

    {{ include('race/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('race_index') }}" class="btn btn-sg btn-primary">back to list</a>

    {{ include('race/_delete_form.html.twig') }}
{% endblock %}

templates/race/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Race index
{% endblock %}

{% block body %}
	<h1>Race index</h1>

	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Name</th>
				<th>Description</th>
				<th>Rate_physical_attack</th>
				<th>Rate_magic_attack</th>
				<th>Rate_physical_resistance</th>
				<th>Rate_magic_resistance</th>
				<th>Rate_physical_stamina</th>
				<th>Rate_magic_stamina</th>
				<th>Rate_speed</th>
				<th>Max_size</th>
				<th>Min_size</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			{% for race in races %}
				<tr>
					<td>{{ race.id }}</td>
					<td>{{ race.name }}</td>
					<td>{{ race.description }}</td>
					<td>{{ race.ratePhysicalAttack }}</td>
					<td>{{ race.rateMagicAttack }}</td>
					<td>{{ race.ratePhysicalResistance }}</td>
					<td>{{ race.rateMagicResistance }}</td>
					<td>{{ race.ratePhysicalStamina }}</td>
					<td>{{ race.rateMagicStamina }}</td>
					<td>{{ race.rateSpeed }}</td>
					<td>{{ race.maxSize }}</td>
					<td>{{ race.minSize }}</td>
					<td>
						<a href="{{ path('race_show', {'id': race.id}) }}" class="btn btn-sg btn-primary">show</a>
						<a href="{{ path('race_edit', {'id': race.id}) }}" class="btn btn-sg btn-primary">edit</a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="13">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	<a href="{{ path('race_new') }}" class="btn btn-sg btn-primary">Create new</a>
{% endblock %}

templates/race/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Race{% endblock %}

{% block body %}
    <h1>Create new Race</h1>

    {{ include('race/_form.html.twig') }}

    <a href="{{ path('race_index') }}" class="btn btn-sg btn-primary">back to list</a>
{% endblock %}

templates/race/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Race
{% endblock %}

{% block body %}
	<h1>Race</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ race.id }}</td>
			</tr>
			<tr>
				<th>Name</th>
				<td>{{ race.name }}</td>
			</tr>
			<tr>
				<th>Description</th>
				<td>{{ race.description }}</td>
			</tr>
			<tr>
				<th>Rate_physical_attack</th>
				<td>{{ race.ratePhysicalAttack }}</td>
			</tr>
			<tr>
				<th>Rate_magic_attack</th>
				<td>{{ race.rateMagicAttack }}</td>
			</tr>
			<tr>
				<th>Rate_physical_resistance</th>
				<td>{{ race.ratePhysicalResistance }}</td>
			</tr>
			<tr>
				<th>Rate_magic_resistance</th>
				<td>{{ race.rateMagicResistance }}</td>
			</tr>
			<tr>
				<th>Rate_physical_stamina</th>
				<td>{{ race.ratePhysicalStamina }}</td>
			</tr>
			<tr>
				<th>Rate_magic_stamina</th>
				<td>{{ race.rateMagicStamina }}</td>
			</tr>
			<tr>
				<th>Rate_speed</th>
				<td>{{ race.rateSpeed }}</td>
			</tr>
			<tr>
				<th>Max_size</th>
				<td>{{ race.maxSize }}</td>
			</tr>
			<tr>
				<th>Min_size</th>
				<td>{{ race.minSize }}</td>
			</tr>
		</tbody>
	</table>

	<a href="{{ path('race_index') }}" class="btn btn-sg btn-primary">back to list</a>

	<a href="{{ path('race_edit', {'id': race.id}) }}" class="btn btn-sg btn-primary">edit</a>

	{{ include('race/_delete_form.html.twig') }}
{% endblock %}